import { sheetDataInterface, sheetKeywordsInterface } from './sheetsInterface';

export class sheetKeywords implements sheetKeywordsInterface {
  constructor(public no: number, public keyword: string) {}
}

export class sheetData implements sheetDataInterface {
  constructor(
    public hotelNo: number,
    public hotelName: string,
    public hotelInformationUrl: string,
    public planListUrl: string,
    public dpPlanListUrl: string,
    public reviewUrl: string,
    public hotelSpecial: string,
    public hotelMinCharge: number,
    public latitude: number,
    public longitude: number,
    public address1: string,
    public address2: string,
    public telephoneNo: string,
    public access: string,
    public parkingInformation: string,
    public nearestStation: string,
    public hotelImageUrl: string,
    public hotelThumbnailUrl: string,
    public roomImageUrl: string,
    public roomThumbnailUrl: string,
    public reviewCount: number,
    public reviewAverage: number,
    public userReview: string,
    public serviceAverage: number,
    public locationAverage: number,
    public roomAverage: number,
    public equipmentAverage: number,
    public bathAverage: number,
    public mealAverage: number,
    public hotelClassCode: string,
    public checkinTime: string,
    public checkoutTime: string,
    public lastCheckinTime: string,
    public hotelRoomNum: number,
    public hasHumidifier: boolean,
    public hasCrib: boolean,
    public hasMiniKitchen: boolean,
    public hasExtensionBed: boolean,
    public hasBigBath: boolean,
    public hasMassageService: boolean,
    public hasOpenAirBath: boolean,
    public hasCourtesyBus: boolean,
    public hasSauna: boolean,
    public hasLounge: boolean,
    public hasCafe: boolean,
    public hasKaraokeRoom: boolean,
    public hasTeaLounge: boolean,
    public hasTableTennis: boolean,
    public hasBeautySalon: boolean,
    public hasGameCorner: boolean,
    public hasBicycleRental: boolean,
    public hasBar: boolean,
    public hasBarLounge: boolean,
    public hasPoolSummerOnly: boolean,
    public hasOutdoorPool: boolean,
    public hasPoolAllYear: boolean,
    public allowedPets: boolean,
    public hasBbqGarden: boolean,
    public hasKaraokeSalon: boolean,
    public hasConvenienceStore: boolean,
    public hasSportsGym: boolean,
    public hasFitnessClub: boolean,
    public hasSkyLounge: boolean,
    public hasChildrenAmusementParkFacility: boolean,
    public hasDrugStore: boolean,
    public hasFishingPond: boolean,
    public hasKidsRoom: boolean,
    public hasHotSpring: boolean,
    public hasFamilyBath: boolean,
    public hasNaturalHotSpring: boolean,
    public hasBedrockBath: boolean,
    public otherId: number,
    public catchCopy: string,
    public caption: string
  ) {}
}
